### ISSUE TITLE
Texte für automatische Mails schreiben

### ISSUE THREAD

**Issue by VeraBrockmeyer** [misterrioes/KanbanForBerlinHousing#13]
Bitte Texte für folgende Mails formulieren:
Bestätigungsmail für Hosts DE/ENG?
Bestätigungsmail für Refugees in ENG/UKR
Erinnerungsmail für Personalausweis DE/ENG?
Erinnerungsmail für Refugees die nicht auf Matching reagieren (e.g. lange offene Vermittlungen) ENG/UKR

**Comment by JuliaB19** [comment]
Alles erledigt, allerdings nur mit russischer "Übersetzung" (via Deepl, sollte vielleicht noch von Ranagul oä überprüft werden). Ukrainisch ist nicht verfügbar auf Deepl, Google traue ich nicht.
